### PR TITLE
Update torchdyn requirement and actions versions

### LINKED ISSUE #3: Tests failing due to sklearn dependency
Waiting on https://github.com/DiffEqML/torchdyn/issues/180

### PR DESCRIPTION
**Pull request by atong01**
## What does this PR do?

Upgrade torchdyn in the requirements after release 1.0.5

Fixes #3 permanently

Fixes requirement to `torch<2.0.0` as `torch>=2.0.0` creates incompatibilities between torch 2 compatible lightning bolt versions and `pytorch-lightning=1.8.3` other utilities should work just fine.

### CODE REVIEW

**Comment by atong01** [comment]
To get tests to pass I had to add torch < 2.0 this is not ideal as torchcfm has no issues with 2.0, but the running package does.

**Comment by atong01** [comment]
Split into runner-requirements.txt (for runner) and requirements.txt (for torchcfm package)

**Comment by kilianFatras** [comment]
does the split requirement split fixes the torch2.0 requirements?

**Comment by atong01** [comment]
yes, runner now requires torch<2 but torchcfm does not

**Pull request merged**
